[build]
  command = "npm install"
  publish = "."
  functions = "functions"

[build.environment]
  NODE_VERSION = "18.18.2"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@zilliz/milvus2-sdk-node"]

[[redirects]]
  from = "/track/pixel/:id"
  to = "/.netlify/functions/track-pixel/:id"
  status = 200

[[redirects]]
  from = "/track/pixel/:id.png"
  to = "/.netlify/functions/track-pixel/:id"
  status = 200

[[redirects]]
  from = "/track/click/:id"
  to = "/.netlify/functions/track-click/:id"
  status = 200

[[redirects]]
  from = "/webhook/mailgun"
  to = "/.netlify/functions/mailgun-webhook"
  status = 200

[[headers]]
  for = "/track/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Cache-Control = "no-cache, no-store, must-revalidate"
